### ISSUE TITLE
Error Reporting for Batch mode

### ISSUE THREAD

**Issue by JAMKuttan** [uzh-dqbm-cmi/PRIDICT#4]
I am attempting to run PRIDICT in batch mode, and keep getting exceptions but I am not able to trace the error itself. I have attached my csv as an example... with this command 
 python pridict_pegRNA_design.py batch --input-fname design.csv --use_5folds --nicking --combine_results

[design.csv](https://github.com/uzh-dqbm-cmi/PRIDICT/files/11771783/design.csv)

```
Calculating features took 19.3 seconds to run.
Deep model took 79.3 seconds to run.
-- Exception occured --
Length of values (2290) does not match length of index (459)
1it [00:28, 28.12s/it]
1it [00:07,  7.46s/it]
1it [00:28, 28.56s/it]

Calculating features took 18.8 seconds to run.
Deep model took 84.2 seconds to run.
-- Exception occured --
Length of values (2289) does not match length of index (459)
1it [00:02,  2.46s/it]

Calculating features took 18.9 seconds to run.
Deep model took 86.2 seconds to run.
-- Exception occured --
Length of values (2292) does not match length of index (459)
1it [00:02,  2.95s/it]
1it [00:01,  1.80s/it]

Calculating features took 29.7 seconds to run.
Deep model took 77.4 seconds to run.
-- Exception occured --
Length of values (3056) does not match length of index (612)
<<< joined row computation process
<<< joined row computation process
<<< joined row computation process
<<< joined row computation process
<<< joined row computation process
***
 Error :( Check your input format is compatible with PRIDICT! More information in input box on https://pridict.it/ ...
***
```

**Comment by mathinic** [comment]
Hello!

Thanks for reaching out and using PRIDICT. I found that the error pops up only with `--combine_results`. Could you give it a go without this option? Meanwhile, I'm on the case to fix it! For now, sticking to individual files is a workaround (and combining them in separate scripts).

All the best,
Nicolas

**Comment by JAMKuttan** [comment]
Thanks! I can confirm it works perfect running without the combine script. Individual files isnt an issue at all! 

P.S. Big fan of your tool. so far, our experiments show high correlation with your scores that are produced. Thanks for putting this together!

**Comment by mathinic** [comment]
Hi JAMKuttan,
Just a brief update, in the meantime we published our updated study with further improved accuracy (also for MMR proficient contexts) here: https://github.com/uzh-dqbm-cmi/PRIDICT2/ https://www.biorxiv.org/content/10.1101/2023.10.09.561414v1

Hope it brings joy/facilitates some designs for you in the future :)

Best,
Nicolas
