### ISSUE TITLE
poly-T filtering

### ISSUE THREAD

**Issue by ov26** [uzh-dqbm-cmi/PRIDICT#7]
Hi!
How does your model deal with poly-T stretches, does it filter them out or are the guides merely scored poorly?

**Comment by mathinic** [comment]
Hi!
Poly-T stretches are not filtered out but have a negative effect on the final score. (as you suggested)
If the polyT are next to the edit on both sides (polyA on the reverse respectively), filtering them out would sometimes remove all pegRNAs.
Best,
Nicolas
